package(default_visibility = ["//visibility:public"])

cc_library(
    name = "code",
    hdrs = ["code.h"],
)

cc_library(
    name = "connection",
    hdrs = ["connection.h"],
    srcs = ["connection.cc"],
    deps = [
        ":code",
    ],
)